---
kind: pipeline
name: default

steps:
- name: test
  image: laradock/workspace:2.6.1-7.2
  commands:
  - php -v
  - composer -V
  - cp .env.example .env
  - composer install --prefer-dist
  - php artisan key:generate
  - ./vendor/bin/phpunit
...
